import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "ENSPD MANAGEMENT SYSTEM",
  description: "Generated by create next app",
};

const LayoutProfesseurs = ({ children }) => {
  return (
    <html>
      {/* <head>
        <script src="https://unpkg.com/react/umd/react.production.min.js"></script>
        <script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/recharts/2.12.7/Recharts.min.js"></script>
      </head> */}
      <body>
        <div className="h-screen flex">
          <div className="md:w-[8%] xl:w-[14%] ">
            <Link className="flex items-center justify-center gap-2" href="/">
              {/* <Image src={null} alt="logo" width={32} height={32} /> */}
              <span className="hidden lg:block font-semibold text-center">
                ENSPD Management System
              </span>
            </Link>

            <Menu />
          </div>
          <div className="md:w-[92%] lg:w-[86%]  xl:w-[86%] bg-[#F7F8FA] ">
            {/* <div className="gradient" /> */}
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
};

export default LayoutProfesseurs;
