export const metadata = {
  title: "ENSPD MANAGEMENT SYSTEM",
  description: "Generated by create next app",
};
const SeConnecter = () => {
  return <div>SeConnecter</div>;
};

export default SeConnecter;
